load("//tools:cpplint.bzl", "cpplint")
load("//tools:apollo_package.bzl", "apollo_package", "apollo_cc_library", "apollo_component", "apollo_cc_test")

package(default_visibility = ["//visibility:public"])

apollo_cc_library(
    name = "apollo_dttf_common",
        srcs = [
            "common.cc"
        ],
        hdrs = [
            "common.h",
            "message.h"
        ],
        deps = [

        ],
)



apollo_package()
cpplint()
